post_install() {
    post_upgrade
}

post_upgrade() {
    systemctl disable --now connman
    systemctl enable --now systemd-timesyncd
    systemctl enable --now systemd-resolved
    systemctl enable --now systemd-networkd
    systemctl enable --now avahi-daemon
    ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
    ln -sf /usr/share/zoneinfo/Europe/London "/etc/localtime"
    echo "LANG=en_GB.UTF-8" > /etc/locale.conf
    sed 's/#en_GB/en_GB/' -i /etc/locale.gen
    locale-gen
}
