#!/bin/sh
cat <<EOF
stages:
  - package-1
  - package-2
  - package-3
  - publish

image: "$CI_REGISTRY_IMAGE/builder"

variables:
  AWS_DEFAULT_REGION: eu-west-1
  BUCKET: $BUCKET

publish:
  stage: publish
  script:
    - ./ci/publish

.local_package:
  script: 
    - ./ci/build-local "\${CI_JOB_NAME}"
  artifacts:
    paths:
      - "pkg/*.pkg.tar.*"
    expire_in: 1 day

pkg/mdaffin/base:
  stage: package-1
  extends: .local_package

pkg/mdaffin/desktop:
  stage: package-2
  extends: .local_package
  needs: ["pkg/mdaffin/base"]

pkg/mdaffin/devel:
  stage: package-2
  extends: .local_package
  needs: ["pkg/mdaffin/base"]

pkg/mdaffin/gaming:
  stage: package-3
  extends: .local_package
  needs: ["pkg/mdaffin/desktop"]
EOF

generate_aur_stage() {
cat <<EOF
${1}:
  stage: package-1
  script: 
    - ./ci/build-aur ${@}
  artifacts:
    paths:
      - "pkg/*.pkg.tar.*"
    expire_in: 1 day
EOF
}

generate_aur_stage aurutils 3.0.3-2 6BC26A17B9B7018A
generate_aur_stage gitlab-cli 0.1.12-2
generate_aur_stage vale 2.4.0-2
